jobs:
  include:
    - stage: "Test"
      language: php
      php:
        - 7.1
        - 7.3
        - 7.4
      before_install:
        - composer install
      script:
        - vendor/bin/phpunit
